blank_issues_enabled: false
contact_links:
  - name:  Necesito Ayuda
    url: https://github.com/TU_USUARIO_GITHUB/Automatizate/discussions
    about:  Preguntas generales, dudas o ayuda con la configuraci贸n
  - name:  Reportar Bug
    url: https://github.com/TU_USUARIO_GITHUB/Automatizate/issues/new?template=bug_report.md
    about:  Reportar un bug o problema en la aplicaci贸n
  - name:  Solicitar Funcionalidad
    url: https://github.com/TU_USUARIO_GITHUB/Automatizate/issues/new?template=feature_request.md
    about:  Sugerir una nueva funcionalidad o mejora
  - name:  Documentaci贸n
    url: https://github.com/TU_USUARIO_GITHUB/Automatizate/wiki
    about:  Gu铆as, tutoriales y documentaci贸n del proyecto
  - name:  Discord
    url: https://discord.gg/automarket
    about:  nete a nuestra comunidad en Discord
  - name:  Email de Soporte
    url: mailto:soporte@automarket.com
    about:  Contacto directo para soporte t茅cnico



